### ISSUE TITLE
Crash on .AddNodaTime()

### ISSUE THREAD

**Issue by GustavEikaas** [shoooe/HotChocolate.Types.NodaTime#2]
When I call the function AddNodaTIme I receive this error:
`services
                .AddGraphQLServer()
                ////
                .ConfigureSchema(x => x.AddNodaTime());`

System.TypeLoadException
  HResult=0x80131522
  Message=Method 'get_RuntimeType' in type 'HotChocolate.Types.NodaTime.DateTimeZoneType' from assembly 'HotChocolate.Types.NodaTime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
  Source=HotChocolate.Types.NodaTime
  StackTrace:
   at HotChocolate.Types.NodaTime.Extensions.ISchemaBuilderExtensions.AddNodaTime(ISchemaBuilder schemaBuilder)
   at webstep.Startup.<>c.<ConfigureServices>b__4_1(ISchemaBuilder x) in C:\Users\Test\Bachelor\webstep\webstep\Startup.cs:line 70
   at Microsoft.Extensions.DependencyInjection.RequestExecutorBuilderExtensions.<>c__DisplayClass0_0.<ConfigureSchema>b__1(IServiceProvider sp, ISchemaBuilder sb)
   at HotChocolate.Execution.RequestExecutorResolver.<CreateSchemaAsync>d__14.MoveNext()

**Comment by StephenDrewLDS** [comment]
Also, it seems to have lost the `netcoreapp3.1` support?

**Comment by shoooe** [comment]
@GustavEikaas What version of the library are you using? What .NET/.NET Core version? What HotChocolate version?

**Comment by shoooe** [comment]
Thanks for reporting.

This repository has been absorbed into [Hot Chocolate](https://github.com/ChilliCream/hotchocolate).

The corresponding Nuget package [HotChocolate.Types.NodaTime](https://www.nuget.org/packages/HotChocolate.Types.NodaTime) is now managed by [ChilliCream](https://www.nuget.org/profiles/ChilliCream).
 
See [this PR](https://github.com/ChilliCream/hotchocolate/pull/3795/files) for reference.
